
import React from 'react';
import { Page, Text, View, Document, StyleSheet } from '@react-pdf/renderer';

const styles = StyleSheet.create({
    page: {
        padding: 30,
        fontFamily: 'Helvetica',
    },
    header: {
        marginBottom: 20,
        borderBottomWidth: 1,
        borderBottomColor: '#111827',
        paddingBottom: 10,
    },
    title: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#111827'
    },
    subtitle: {
        fontSize: 12,
        color: '#6b7280',
        marginTop: 4
    },
    section: {
        marginBottom: 20,
        padding: 10,
    },
    sectionTitle: {
        fontSize: 16,
        fontWeight: 'bold',
        marginBottom: 10,
        color: '#4f46e5',
        textTransform: 'uppercase'
    },
    text: {
        fontSize: 11,
        lineHeight: 1.5,
        marginBottom: 5,
        color: '#374151'
    },
    table: {
        display: "flex",
        width: "auto",
        borderStyle: "solid",
        borderWidth: 1,
        borderRightWidth: 0,
        borderBottomWidth: 0,
        marginTop: 10
    },
    tableRow: {
        margin: "auto",
        flexDirection: "row"
    },
    tableCol: {
        width: "33%",
        borderStyle: "solid",
        borderWidth: 1,
        borderLeftWidth: 0,
        borderTopWidth: 0
    },
    tableCell: {
        margin: "auto",
        marginTop: 5,
        fontSize: 10
    }
});

interface HandoffProps {
    summary: any;
    timeline: any[];
    redFlags: any[];
}

export const HandoffDocument = ({ summary, timeline, redFlags }: HandoffProps) => (
    <Document>
        <Page size="A4" style={styles.page}>

            {/* Header */}
            <View style={styles.header}>
                <Text style={styles.title}>Lawyer Handoff Pack</Text>
                <Text style={styles.subtitle}>Generated by LegalIntake AI • {new Date().toLocaleDateString()}</Text>
            </View>

            {/* Case Summary */}
            <View style={styles.section}>
                <Text style={styles.sectionTitle}>Case Summary: {summary.client}</Text>
                <Text style={styles.text}>Incident Date: {summary.incidentDate}</Text>
                <Text style={styles.text}>Status: {summary.status}</Text>
                <Text style={styles.text}>Description: {summary.description}</Text>
            </View>

            {/* Red Flags */}
            <View style={styles.section}>
                <Text style={styles.sectionTitle}>Risk Analysis (Red Flags)</Text>
                {redFlags.map((flag, i) => (
                    <Text key={i} style={{ ...styles.text, color: '#b91c1c' }}>
                        • [{flag.severity}] {flag.message}
                    </Text>
                ))}
            </View>

            {/* Timeline */}
            <View style={styles.section}>
                <Text style={styles.sectionTitle}>Chronological Timeline</Text>
                {timeline.map((item, i) => (
                    <Text key={i} style={styles.text}>
                        {item.date} - {item.event} ({item.type})
                    </Text>
                ))}
            </View>

        </Page>
    </Document>
);
